### ISSUE TITLE
Need to check for MaxUploadSize > 0

### ISSUE THREAD

**Issue by rdogmartin** [RickStrahl/Westwind.plUploadHandler#1]
I included your handler in the beta of Gallery Server Pro I just released as it was better than the one I wrote. A user just reported an issue where a "file too large" message is sent to the user when MaxUploadSize = 0 (unlimited).

In line 93 of plUploadBaseHandler.cs you have:

```
if (chunk == 0 && Request.ContentLength * (chunks - 1) > MaxUploadSize)
```

I think it needs a check for when MaxUploadSize > 0:

```
if (chunk == 0 && MaxUploadSize > 0 && Request.ContentLength * (chunks - 1) > MaxUploadSize)
```

Cheers,
Roger

**Comment by RickStrahl** [comment]
Hi Roger,

Thanks good catch. Fixed…

Aloha,

+++ Rick ---

Rick Strahl

West Wind Technologies

 http://www.west-wind.com/ www.west-wind.com

 http://www.west-wind.com/weblog http://www.west-wind.com/weblog

 http://twitter.com/RickStrahl http://twitter.com/RickStrahl
